# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'chapter_05' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chapter_05
  pod 'RxSwift', '~> 5'
  pod 'RxRelay', '~> 5'
end
