# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

 use_frameworks!

target 'my rxSwift' do
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxRelay', '~> 5'

end
