# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

# Pods for chapter_03
 target 'chapter_03' do

pod 'RxSwift', '~> 5'
pod 'RxRelay', '~> 5'
pod 'RxCocoa', '~> 5'
end
